In [8]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
# 00으로 초기화된 배열
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# 빈 값으로 만들어진 배열
arr = np.empty((4,3))
print(arr)

[[3.20325762e-316 6.79038654e-313 6.79038653e-313]
 [2.37663529e-312 2.58883487e-312 2.41907520e-312]
 [2.44029516e-312 1.08221785e-312 1.08221785e-312]
 [2.02566915e-322 2.12199579e-314 4.44659081e-323]]


In [13]:
# 1로 가득찬 배열
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#배열의 생성
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
# 배열의 모양
arr.shape

(2, 3)

In [24]:
# 차원
arr.ndim #dimension

2

In [25]:
# 데이터 타입
arr.dtype

dtype('int64')

In [32]:
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [35]:
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [37]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [38]:
# ndarray 배열의 연산
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [39]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [41]:
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [43]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [42]:
np.multiply(arr1,arr2)
# np.add나 multiply 혹은 연산기호를 쓰든 개인 취향의 영역

array([[ 5, 12],
       [21, 32]])

In [45]:
# ndarray 배열 슬라이싱 하기

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [49]:
arr[0,2]

3

In [51]:
arr[[0,1,2],[2,0,1]]

array([3, 4, 8])

In [53]:
idx = arr > 3
print(idx) # 값을 T,F로 표시

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [54]:
print(arr[idx]) # idx를 매개변수로 줘서 True값만 가져옴.

[4 5 6 7 8 9]


In [61]:
# numpy사용해서 csv 배열로 불러오기
redwine=np.loadtxt(fname='winequality-red.csv', delimiter=';',skiprows=1) #옛날 라이브러리이기에 줄임말을 많이 씀. delimiter : sep , skiprows : header
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [62]:
 # 합계
print(redwine.sum())

152084.78194


In [66]:
# 평균
print(redwine.mean())

7.926036165311652


In [71]:
print(redwine.sum(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [68]:
print(redwine.sum(1))

[ 74.5438  123.0548   99.699   ... 100.48174 105.21547  92.49249]


In [70]:
print(redwine.mean(axis=0))

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [72]:
redwine[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [73]:
redwine[0,:]

array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ,  5.    ])

In [75]:
redwine.max(axis=0)

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [76]:
redwine.min(axis=0)

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])